- name: List kieker log directories
  shell: find /tmp/kieker-20* -type f
  register: remote_file_paths
  sudo: yes

- name: Copy kieker log
  fetch:
    src={{ item }}
    dest={{ log_path }}
  with_items: remote_file_paths.stdout_lines
  sudo: yes
