- name: Add java runtime options for kieker to setenv.sh
  lineinfile:
    dest=/usr/share/tomcat7/bin/setenv.sh
    insertafter=EOF
    line='CATALINA_OPTS="$CATALINA_OPTS -javaagent:/usr/share/tomcat7/bin/kieker-{{ kieker_version }}-aspectj.jar -Dkieker.monitoring.configuration=/usr/share/tomcat7/bin/kieker.monitoring.properties -Dkieker.monitoring.skipDefaultAOPConfiguration=true"'
    state=present
    create=yes
  sudo: yes

- name: Download kieker aspectj to /usr/share/tomcat7/bin/.
  get_url:
    url={{ kieker_download_url }}
    dest=/usr/share/tomcat7/bin/kieker-{{ kieker_version }}-aspectj.jar
    force=yes
  sudo: yes

- name: Download kieker aspectj to /usr/share/tomcat7/lib/.
  get_url:
    url={{ kieker_download_url }}
    dest=/usr/share/tomcat7/lib/kieker-{{ kieker_version }}-aspectj.jar
    force=yes
  sudo: yes

- name: Copy kieker properties file
  template:
    src=kieker.monitoring.properties
    dest=/usr/share/tomcat7/bin/kieker.monitoring.properties
  sudo: yes
