- hosts: all
  roles:
    - { role: 'setup-common',
    tags: [ 'setup', 'common' ],
  }

- hosts: all
  roles:
    - { role: 'setup-kieker-resource-monitor',
    kieker_monitoring_name: KIEKER-RESOURCE-MONITOR,
    when: monitoring_framework is defined and monitoring_framework == 'kieker',
    tags: [ 'setup', 'kieker' ],
  }

- hosts: loadbalancer
  roles:
    - { role: 'setup-loadbalancer',
    tags: [ 'setup', 'loadbalancer' ],
  }

- hosts: recipes
  roles:
    - { role: 'setup-recipes',
    tags: [ 'setup', 'recipes' ],
  }

- hosts: recipes
  roles:
    - { role: 'setup-kieker-recipes',
    kieker_monitoring_name: KIEKER-INSTRUMENTATION,
    when: monitoring_framework is defined and monitoring_framework == 'kieker',
    tags: [ 'setup', 'recipes', 'kieker' ],
  }

- hosts: tomcat
  roles:
    - { role: 'setup-tomcat',
    tags: [ 'setup', 'tomcat' ],
  }

- hosts: eureka
  roles:
    - { role: 'setup-kieker-tomcat',
    kieker_monitoring_name: KIEKER-INSTRUMENTATION,
    tags: [ 'setup', 'tomcat', 'kieker' ],
    when: monitoring_framework is defined and monitoring_framework == 'kieker',
  }

- hosts: eureka
  roles:
    - { role: 'setup-eureka',
    tags: [ 'setup', 'eureka' ],
  }

- hosts: eureka
  roles:
    - { role: 'setup-kieker-eureka',
    kieker_monitoring_name: KIEKER-INSTRUMENTATION,
    tags: [ 'setup', 'eureka', 'kieker' ],
    when: monitoring_framework is defined and monitoring_framework == 'kieker',
  }

- hosts: rssserver
  roles:
    - { role: 'setup-rssserver',
    tags: [ 'setup', 'rssserver' ],
  }

- hosts: database
  roles:
    - { role: 'setup-database',
    tags: [ 'setup', 'database' ],
  }

- hosts: client
  roles:
    - { role: 'setup-client',
    tags: [ 'setup', 'client' ],
    when: generate_requests is defined and generate_requests == true,
  }
