- name: List recipes log files
  shell: find {{ recipes_dir }}/logs/*
  register: remote_file_paths
  ignore_errors: yes

- name: Copy recipes log files
  fetch:
    src={{ item }}
    dest={{ copy_log_path }}
  with_items: remote_file_paths.stdout_lines
  when: remote_file_paths.rc == 0
