- name: Check and add cassandra debian repository
  apt_repository: repo='deb http://www.apache.org/dist/cassandra/debian 20x main' state=present
  sudo: yes

- name: Check and add keys for the cassandra debian repo
  apt_key: keyserver={{ item.key }} id={{ item.id }}
  with_items:
    - { key: 'pgp.mit.edu', id: 'F758CE318D77295D' }
    - { key: 'pgp.mit.edu', id: '2B5C1B00' }
    - { key: 'pgp.mit.edu', id: '0353B12C' }
  sudo: yes

- name: Check installed packages
  apt: name={{ item }} state=present force=yes update_cache=yes
  with_items:
    - openjdk-7-jre
    - cassandra
  sudo: yes
