- name: Check installed packages
  apt: name={{ item }} state=present force=yes update_cache=yes
  with_items:
    - openjdk-7-jre
  sudo: yes

- name: Check if kieker binary release directory exists
  stat: path={{ kieker_binary_release_dir }}
  register: kieker_binary_release

- name: Download kieker binary
  get_url:
    url={{ kieker_binary_release_download_url }}
    dest=/tmp/kieker-{{ kieker_version }}-binary.zip
    force=no
  when: kieker_binary_release.stat.exists == false

- name: Unarchive kieker binary
  unarchive:
    src=/tmp/kieker-{{ kieker_version }}-binary.zip
    dest={{ kieker_binary_release_parent_dir }}
    copy=no
  when: kieker_binary_release.stat.exists == false

- name: Copy kieker properties file
  copy:
    src=kieker.monitoring.properties
    dest={{ kieker_binary_release_dir }}/kieker.monitoring.properties

- name: Copy kieker resource monitor control script
  copy:
    src=kieker-resource-monitor-control.sh
    dest={{ kieker_binary_release_dir }}/kieker-resource-monitor-control.sh
    mode=0755
