# A workaround to route network traffic through local links in emulab
- name: Change hostname from FQDN to short name
  hostname: name={{ inventory_hostname }}
  when: use_short_hostname is defined and use_short_hostname == true
  sudo: yes
