# A workaround to route network traffic through local links in emulab
- name: Change hostname (a workaround for emulab)
  hostname: name={{ ansible_hostname }}
  when: hardware_platform == 'emulab'
  sudo: yes
