# A workaround to route network traffic through local links in emulab
- name: Change hostname (a workaround for emulab)
  hostname: name={{ inventory_hostname }}
  when: hardware_platform is defined and hardware_platform == 'emulab'
  sudo: yes
