# A workaround to route network traffic through local links in emulab
- name: Change hostname from FQDN to short name
  hostname: name={{ inventory_hostname }}
  when: change_hostname is defined and change_hostname == 'yes'
  sudo: yes
