- name: Delete recipes log files
  file: path={{ item }} state=absent
  with_items:
    - "{{ recipes_dir }}/logs/rss-edge.log"
    - "{{ recipes_dir }}/logs/rss-middletier.log"
    - "{{ recipes_dir }}/logs/edge-control.log"
    - "{{ recipes_dir }}/logs/middletier-control.log"
