- name: List nginx log files
  shell: find /var/log/nginx/*
  register: remote_file_paths
  sudo: yes
  ignore_errors: yes

- name: Copy nginx log files
  fetch:
    src={{ item }}
    dest={{ copy_log_path }}
  with_items: remote_file_paths.stdout_lines
  when: remote_file_paths.rc == 0
  sudo: yes
