- name: Download kieker aspectj
  get_url:
    url={{ kieker_download_url }}
    dest={{ recipes_dir }}/kieker-{{ kieker_version }}-aspectj.jar
    force=yes

- name: Copy kieker properties file
  copy:
    src=kieker.monitoring.properties
    dest={{ recipes_dir }}/kieker.monitoring.properties

- name: Ensure that META-INF directory exists in edge and middletier
  file:
    path={{ recipes_dir }}/{{ item }}/build/libs/META-INF/
    state=directory
  with_items:
    - rss-edge
    - rss-middletier

- name: Copy aop.xml to edge
  copy:
    src=aop-edge.xml
    dest={{ recipes_dir }}/rss-edge/build/libs/META-INF/aop.xml

- name: Update edge jar with aop.xml
  shell: zip -r rss-edge-0.1.0-SNAPSHOT.jar META-INF
    chdir={{ recipes_dir }}/rss-edge/build/libs/

- name: Copy aop.xml to middletier
  copy:
    src=aop-middletier.xml
    dest={{ recipes_dir }}/rss-middletier/build/libs/META-INF/aop.xml

- name: Update middletier jar with aop.xml
  shell: zip -r rss-middletier-0.1.0-SNAPSHOT.jar META-INF
    chdir={{ recipes_dir }}/rss-middletier/build/libs/

- name: Copy edge-kieker control script
  template:
    src=edge-kieker-control.sh
    dest={{ recipes_dir }}
    mode=0755

- name: Copy middletier-kieker control script
  template:
    src=middletier-kieker-control.sh
    dest={{ recipes_dir }}
    mode=0755
