- name: Wait 2 min for system to startup
  pause: minutes=2

- name: Start JMeter
  shell: ./tmp/apache-jmeter-2.13/bin/jmeter -n -t /tmp/TestPlan.jmx -l /tmp/jmeter-log/result.jtl -j /tmp/jmeter-log/jmeter.log
  async: 86400
  poll: 60
