- name: List cassandra log files
  shell: find /var/log/cassandra/*
  register: remote_file_paths
  sudo: yes

- name: Copy cassandra log files
  fetch:
    src={{ item }}
    dest={{ log_path }}
  with_items: remote_file_paths.stdout_lines
  sudo: yes
