- name: List tomcat log files
  shell: find /var/log/tomcat7/*
  register: remote_file_paths
  sudo: yes

- name: Delete tomcat log files
  file: path={{ item }} state=absent
  with_items: remote_file_paths.stdout_lines
  sudo: yes
