- name: Check installed packages
  apt:
    name={{ item }}
    state=present
    update_cache=yes
    cache_valid_time=3600
  with_items:
    - java7-jdk
    - git
    - gradle
  sudo: yes
  register: result
  changed_when: "'Unpacking' in result.stdout"
