- name: Check installed packages
  apt: name={{ item }} state=present
  with_items:
    - java7-jdk
    - git
    - gradle
  sudo: yes
  register: result
  changed_when: "'Unpacking' in result.stdout"
