- name: List tomcat log files
  shell: find /var/log/tomcat7/*
  register: remote_file_paths
  sudo: yes

- name: Copy tomcat log files
  fetch:
    src={{ item }}
    dest={{ log_path }}
  with_items: remote_file_paths.stdout_lines
  sudo: yes
