- name: Stop tomcat before configuring
  service:
    name=tomcat7
    state=stopped
  sudo: yes

# TODO use replace
- name: Copy server.xml to /etc/tomcat7/
  copy: src=server.xml dest=/etc/tomcat7/ backup=yes
  sudo: yes

# TODO use replace
- name: Copy tomcat7 to /etc/default/
  copy: src=tomcat7 dest=/etc/default/ backup=yes
  sudo: yes

- name: Set authbind
  file:
    path=/etc/authbind/byport/80
    state=touch
    mode=0500
    owner=tomcat7
  sudo: yes

#- name: Make sure that log directory exists
#  file: path=/var/log/tomcat7
#    state=directory
#    owner=tomcat7
#    group=tomcat7
#    mode=0644
#  sudo: yes
