- name: List nginx log files
  shell: find /var/log/nginx/*
  register: remote_file_paths
  sudo: yes

- name: Delete nginx log files
  file: path={{ item }} state=absent
  with_items: remote_file_paths.stdout_lines
  sudo: yes
